# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.FileField(upload_to='C:\\Users\\Gustavo\\Desktop\\Dojo-Assignments\\Python\\django\\fileupload_project\\MEDIA')),
            ],
        ),
    ]
